import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { cn } from "@shared/lib";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang='en' suppressHydrationWarning>
    <body className={cn("container", geistSans.variable)}>{children}</body>
  </html>
);
export default RootLayout;
